version: "3.9"
name: night-planet-work
services:

  web-public-night-planet-work:
    container_name: web-public-night-planet-work
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - '8090:80'
      - '443:443'
    networks:
      - night-planet-network-work
    tty: true
    depends_on:
      - app-public-night-planet-work
    volumes:
      - .:/var/www/html
    environment:
      - VIRTUAL_HOST=${APP_URL}

  web-admin-night-planet-work:
    container_name: web-admin-night-planet-work
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - '8091:80'
      - '1443:443'
    networks:
      - night-planet-network-work
    tty: true
    depends_on:
      - app-admin-night-planet-work
    volumes:
      - .:/var/www/html
    environment:
      - VIRTUAL_HOST=${APP_ADMIN_URL}

  app-public-night-planet-work:
    container_name: app-public-night-planet-work
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./:/var/www/html
    expose:
      - 9000
    networks:
      - night-planet-network-work
    tty: true
    depends_on:
      - db-night-planet-work
    environment:
      - VIRTUAL_HOST=${APP_URL}

  app-admin-night-planet-work:
    container_name: app-admin-night-planet-work
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./:/var/www/html
    expose:
      - 9000
    networks:
      - night-planet-network-work
    tty: true
    depends_on:
      - db-night-planet-work
    environment:
      - VIRTUAL_HOST=${APP_ADMIN_URL}

  cron-night-planet-work:
    container_name: cron-night-planet-work
    build:
      context: .
      dockerfile: ./docker/cron/Dockerfile
    volumes:
      - ./:/var/www/html
    expose:
      - 9000
    networks:
      - night-planet-network-work
    tty: true
    depends_on:
      - db-night-planet-work

  db-night-planet-work:
    container_name: db-night-planet-work
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports:
      - 23306:3306
      - 23060:33060
    networks:
      - night-planet-network-work
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      TZ: 'Asia/Tokyo'
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql-volume:/var/lib/mysql
      - ./docker/db/initdb:/docker-entrypoint-initdb.d

networks:
  night-planet-network-work:
    external: true

volumes:
  mysql-volume:
  maildir: {}
  minio: